### ISSUE TITLE
关于简历项目经验部分的几个问题

### ISSUE THREAD

**Issue by gamedebug** [mark-stars/practice-#1]
项目1：项目用户量多大？访问量多大？两个集群规模多大？作为一个安装源服务，web集群只需要提供简单的静态页面服务即可，没有后端数据依赖，不存在脑裂；ceph集群本来就不会脑裂，这是人家软件自身的特性。那么你提到的“不会脑裂”是想体现你哪方面的技术优势？或者你给我解释一下什么叫脑裂？还有你在这个项目里具体角色是什么？你做里哪些工作？整个搭建维护流程中有没有碰到什么问题？如何解决的？

项目2：客户是谁？有多少？需求是什么？交流的目的是什么？（谈业务？寻求技术解决方案？）交流的平台用的什么软件？是你设计编写的？用于运行交流平台的web集群规模多大？什么架构？是你设计规划的么？设计规划的技术依据是什么？还是前面那个问题，你到底干了什么？软件开发？平台设计？平台搭建？平台维护？

项目3：监控目标是一套什么样的系统？跑了哪些业务？提供什么功能？用户是谁？系统规模多大？你的监控平台规模又有多大？几个server几个agent？agent工作模式用的主动还是被动？为什么？每天在平台上通过哪些常用监控项收集哪些监控数据？收过来的数据你们作何处置？如何设置各项的告警阈值？告警采用何种方式通知？收到各种不同的告警信息你们会采取何种技术应对手段？

所有项目：项目团队多少人？你的职责是什么？你向谁汇报工作？汇报频率如何？各项目的运维规范是什么？工作中遇到的各种系统错误如何发现、定位、解决？每个项目能否举例说明？

**Comment by mark-stars** [comment]
老师，我已收到，今晚11点之前完成。

**Comment by mark-stars** [comment]
陆老师 已完成修改
